### ISSUE TITLE
Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by jurelou** [gnieser/quasar-keycloak#2]
Everything work as expected unless I try to logout.

![image](https://user-images.githubusercontent.com/30180021/192348721-ea701177-08ac-4e12-83c3-5c062fe85188.png)

Here is my keycloack client config: (keycloack legacy v19)

![image](https://user-images.githubusercontent.com/30180021/192348955-96526713-5dba-4c33-88f9-0f2e9c38b809.png)

Do you have any idea why ?

**Comment by gnieser** [comment]
I haven't updated the dependencies of this repository as it is just a bug reproducer.

What you are seeing in a mismatch between the new versions of Keycloak and the package used. More precisely since version 18 (https://www.keycloak.org/2022/04/keycloak-1800-released), it adopted OpenID Connect Logout and the logout parameter changed. It should work with a up-to-date version of keycloak-js.
